### ISSUE TITLE
OpenapiClient::PrimaryTransaction NameError

### ISSUE THREAD

**Issue by trevorrjohn** [GBSEcom/Ruby#1]
Trying to install and test the gem however I encountered this error when following the README.

```
$ gem install first_data_gateway
Successfully installed first_data_gateway-1.7.0
1 gem installed
$ irb -r openapi_client
/Users/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/first_data_gateway-1.7.0/lib/openapi_client/models/ach_credit_transaction.rb:17:in `<module:OpenapiClient>': uninitialized constant OpenapiClient::PrimaryTransaction (NameError)
	from /Users/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/first_data_gateway-1.7.0/lib/openapi_client/models/ach_credit_transaction.rb:15:in `<top (required)>'
	from /Users/user/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	from /Users/user/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	from /Users/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/first_data_gateway-1.7.0/lib/openapi_client.rb:27:in `<top (required)>'
	from /Users/user/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `require'
	from /Users/user/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `rescue in require'
	from /Users/user/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:156:in `require'
	from /Users/user/.rbenv/versions/2.7.1/lib/ruby/2.7.0/irb/init.rb:288:in `block in load_modules'
	from /Users/user/.rbenv/versions/2.7.1/lib/ruby/2.7.0/irb/init.rb:286:in `each'
	from /Users/user/.rbenv/versions/2.7.1/lib/ruby/2.7.0/irb/init.rb:286:in `load_modules'
	from /Users/user/.rbenv/versions/2.7.1/lib/ruby/2.7.0/irb/init.rb:21:in `setup'
	from /Users/user/.rbenv/versions/2.7.1/lib/ruby/2.7.0/irb.rb:392:in `start'
	from /Users/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/irb-1.2.3/exe/irb:11:in `<top (required)>'
	from /Users/user/.rbenv/versions/2.7.1/bin/irb:23:in `load'
	from /Users/user/.rbenv/versions/2.7.1/bin/irb:23:in `<main>'
/Users/user/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- openapi_client (LoadError)
	from /Users/user/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /Users/user/.rbenv/versions/2.7.1/lib/ruby/2.7.0/irb/init.rb:288:in `block in load_modules'
	from /Users/user/.rbenv/versions/2.7.1/lib/ruby/2.7.0/irb/init.rb:286:in `each'
	from /Users/user/.rbenv/versions/2.7.1/lib/ruby/2.7.0/irb/init.rb:286:in `load_modules'
	from /Users/user/.rbenv/versions/2.7.1/lib/ruby/2.7.0/irb/init.rb:21:in `setup'
	from /Users/user/.rbenv/versions/2.7.1/lib/ruby/2.7.0/irb.rb:392:in `start'
	from /Users/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/irb-1.2.3/exe/irb:11:in `<top (required)>'
	from /Users/user/.rbenv/versions/2.7.1/bin/irb:23:in `load'
	from /Users/user/.rbenv/versions/2.7.1/bin/irb:23:in `<main>'
```

Let me know what you think.

**Comment by ericmargules** [comment]
@trevorrjohn thank you for bringing this to my attention. I pushed a new gem version. Can you update to 1.7.1 and give it another try. This should resolve the issue.
